(cl:defpackage cam_tracker-srv
  (:use )
  (:export
   "CHANGETRACKINGMODE"
   "<CHANGETRACKINGMODE-REQUEST>"
   "CHANGETRACKINGMODE-REQUEST"
   "<CHANGETRACKINGMODE-RESPONSE>"
   "CHANGETRACKINGMODE-RESPONSE"
  ))

