// Generated by gencpp from file cam_tracker/ChangeTrackingMode.msg
// DO NOT EDIT!


#ifndef CAM_TRACKER_MESSAGE_CHANGETRACKINGMODE_H
#define CAM_TRACKER_MESSAGE_CHANGETRACKINGMODE_H

#include <ros/service_traits.h>


#include <cam_tracker/ChangeTrackingModeRequest.h>
#include <cam_tracker/ChangeTrackingModeResponse.h>


namespace cam_tracker
{

struct ChangeTrackingMode
{

typedef ChangeTrackingModeRequest Request;
typedef ChangeTrackingModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeTrackingMode
} // namespace cam_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cam_tracker::ChangeTrackingMode > {
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::cam_tracker::ChangeTrackingMode&) { return value(); }
};

template<>
struct DataType< ::cam_tracker::ChangeTrackingMode > {
  static const char* value()
  {
    return "cam_tracker/ChangeTrackingMode";
  }

  static const char* value(const ::cam_tracker::ChangeTrackingMode&) { return value(); }
};


// service_traits::MD5Sum< ::cam_tracker::ChangeTrackingModeRequest> should match 
// service_traits::MD5Sum< ::cam_tracker::ChangeTrackingMode > 
template<>
struct MD5Sum< ::cam_tracker::ChangeTrackingModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cam_tracker::ChangeTrackingMode >::value();
  }
  static const char* value(const ::cam_tracker::ChangeTrackingModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam_tracker::ChangeTrackingModeRequest> should match 
// service_traits::DataType< ::cam_tracker::ChangeTrackingMode > 
template<>
struct DataType< ::cam_tracker::ChangeTrackingModeRequest>
{
  static const char* value()
  {
    return DataType< ::cam_tracker::ChangeTrackingMode >::value();
  }
  static const char* value(const ::cam_tracker::ChangeTrackingModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cam_tracker::ChangeTrackingModeResponse> should match 
// service_traits::MD5Sum< ::cam_tracker::ChangeTrackingMode > 
template<>
struct MD5Sum< ::cam_tracker::ChangeTrackingModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cam_tracker::ChangeTrackingMode >::value();
  }
  static const char* value(const ::cam_tracker::ChangeTrackingModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam_tracker::ChangeTrackingModeResponse> should match 
// service_traits::DataType< ::cam_tracker::ChangeTrackingMode > 
template<>
struct DataType< ::cam_tracker::ChangeTrackingModeResponse>
{
  static const char* value()
  {
    return DataType< ::cam_tracker::ChangeTrackingMode >::value();
  }
  static const char* value(const ::cam_tracker::ChangeTrackingModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAM_TRACKER_MESSAGE_CHANGETRACKINGMODE_H
